apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathnex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathnex
  template:
    metadata:
      labels:
        app: pathnex
    spec:
      containers:
        - name: pathnex
          image: 067744548992.dkr.ecr.ap-south-1.amazonaws.com/pathnex-app:1.0
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
